# Generated by Django 5.0.7 on 2024-07-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_product_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_premium',
            field=models.BooleanField(default=True),
        ),
    ]
